# Generated by Django 5.0.7 on 2024-07-29 05:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('authorized', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_sca.department')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_sca.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='django_sca.department')),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='django_sca.person')),
            ],
        ),
    ]
