# Generated by Django 5.0.7 on 2024-07-16 04:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 7, 15, 23, 32, 58, 980933))),
                ('authorized', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_sca.department')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_sca.person')),
            ],
        ),
    ]
