# Generated by Django 5.0.7 on 2024-07-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondepart',
            old_name='departmentId',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='persondepart',
            old_name='personId',
            new_name='person',
        ),
    ]
